FROM node:14.16.0-alpine3.13 AS buil-stage

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build


# Step 2 
FROM nginx:1.12-alpine 

RUN addgroup app && adduser -S -G app app
USER app
COPY /app/build /usr/share/nginx/html
EXPOSE 3000

ENTRYPOINT [ "nginx", "-g", "daemon off"]



